const [treinos, setTreinos] = useState({
    'Treino A': [
      { id: 'a1', nome: 'Supino Reto', selecionado: false },
      { id: 'a2', nome: 'Rosca direta c/ barra', selecionado: false },
      { id: 'a3', nome: 'Supino inclinado', selecionado: false },
      { id: 'a4', nome: 'Rosca alternada', selecionado: false },
      { id: 'a5', nome: 'Supino declinado', selecionado: false },
      { id: 'a6', nome: 'Rosca concentrada', selecionado: false },
      { id: 'a7', nome: 'Supino mãos aproximadas', selecionado: false },
      { id: 'a8', nome: 'Antebraços c/ barra', selecionado: false },
      { id: 'a9', nome: 'Rosca martelo', selecionado: false }, // Adicionado aqui!
      { id: 'a10', nome: 'Supino c/ halteres', selecionado: false },
      { id: 'a11', nome: 'Crucifixo c/ halteres', selecionado: false },
      { id: 'a12', nome: 'Supino inclinado c/ halteres', selecionado: false },
      { id: 'a13', nome: 'Crucifixo incli. c/ halteres', selecionado: false },
      { id: 'a14', nome: 'Peito estação', selecionado: false },
      { id: 'a15', nome: 'Abdominal', selecionado: false },
    ],
    'Treino B': [
      { id: 'b1', nome: 'Puxada alta frontal', selecionado: false },
      { id: 'b2', nome: 'Puxada alta mãos prox.', selecionado: false },
      { id: 'b3', nome: 'Tríceps barra reta', selecionado: false },
      { id: 'b4', nome: 'Puxada braços esticados', selecionado: false },
      { id: 'b5', nome: 'Tríceps corda', selecionado: false },
      { id: 'b6', nome: 'Remada sentado', selecionado: false },
      { id: 'b7', nome: 'Tríceps coice', selecionado: false },
      { id: 'b8', nome: 'Serrote', selecionado: false },
      { id: 'b9', nome: 'Pux. vert. c/ barra mãos juntas', selecionado: false },
      { id: 'b10', nome: 'Levantamento terra', selecionado: false },
      { id: 'b11', nome: 'Elev/abdução escápulas', selecionado: false },
      { id: 'b12', nome: 'Remada curvada pronada', selecionado: false },
      { id: 'b13', nome: 'Remada curvada', selecionado: false },
      { id: 'b14', nome: 'Abdominal', selecionado: false },
    ],
    'Treino C': [
      { id: 'c1', nome: 'Ombro estação', selecionado: false },
      { id: 'c2', nome: 'Extensão pernas', selecionado: false },
      { id: 'c3', nome: 'Des. sentado c/ halteres', selecionado: false },
      { id: 'c4', nome: 'Flexão pernas', selecionado: false },
      { id: 'c5', nome: 'Elev. frontal c/ halteres', selecionado: false },
      { id: 'c6', nome: 'Prensa hack squat', selecionado: false },
      { id: 'c7', nome: 'Elev. lateral c/ halteres', selecionado: false },
      { id: 'c8', nome: 'Leg press inclinado', selecionado: false },
      { id: 'c9', nome: 'Elev. lateral tronco p/ frente', selecionado: false },
      { id: 'c10', nome: 'Agachamento c/ barra', selecionado: false },
      { id: 'c11', nome: 'Des. c/ barra atrás da nuca', selecionado: false },
      { id: 'c12', nome: 'Des. c/ barra frente', selecionado: false },
      { id: 'c13', nome: 'Deltóide sent. rot. do punho', selecionado: false },
      { id: 'c14', nome: 'Abdominal', selecionado: false },
    ]
  });